### ISSUE TITLE
simper.pretty

### ISSUE THREAD

**Issue by LorgasBG** [asteinberger9/seq_scripts#6]
Hi, 
I have been running simper without problems 
simper(fourth_root_sqrt_OTU_abundances_relative, AGDX_samples$Fjord, permutations=1000)

However, when I tried to repeat the analysis with simper.pretty 
simper.pretty(fourth_root_sqrt_OTU_abundances_relative, AGDX_samples, c('Fjord'), perc_cutoff=1, low_cutoff = 'y', low_val=0.01, '_relative_abundances')

I get an error message: Error in tapply(x, group, mean) : arguments must have same length

I am just wondering if someone else have reported the same error or it is actually something with the format of my files. 
Thanks in advance,
Lorgas

**Comment by asteinberger9** [comment]
Hi @LorgasBG, I apologize for my extremely late reply to your issue. The error message generated is often caused by incorrect formatting of either your OTU or metadata table. Please refer to the README for details on what acceptable input formats are for these scripts and doublecheck that your inputs comply. I hope you were already able to figure it out or found an alternative approach for your analysis.
